// Mocks generated by Mockito 5.4.5 from annotations
// in gemorph_flutter/test/screens/upload_dna_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:gemorph_flutter/services/report_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeReport_0 extends _i1.SmartFake implements _i2.Report {
  _FakeReport_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_1 extends _i1.SmartFake implements Uri {
  _FakeUri_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ReportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportService extends _i1.Mock implements _i2.ReportService {
  MockReportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> uploadDNA(_i4.Uint8List? bytes, String? filename) =>
      (super.noSuchMethod(
            Invocation.method(#uploadDNA, [bytes, filename]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#uploadDNA, [bytes, filename]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Stream<_i2.ReportProgress> waitForCompletion(
    String? fileId, {
    Duration? pollInterval = const Duration(seconds: 10),
    int? maxTries = 60,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #waitForCompletion,
              [fileId],
              {#pollInterval: pollInterval, #maxTries: maxTries},
            ),
            returnValue: _i3.Stream<_i2.ReportProgress>.empty(),
          )
          as _i3.Stream<_i2.ReportProgress>);

  @override
  _i3.Future<_i2.Report> getReport(String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#getReport, [fileId]),
            returnValue: _i3.Future<_i2.Report>.value(
              _FakeReport_0(this, Invocation.method(#getReport, [fileId])),
            ),
          )
          as _i3.Future<_i2.Report>);

  @override
  Uri pdfUrl(String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#pdfUrl, [fileId]),
            returnValue: _FakeUri_1(this, Invocation.method(#pdfUrl, [fileId])),
          )
          as Uri);

  @override
  _i3.Future<List<_i2.Report>> listReports() =>
      (super.noSuchMethod(
            Invocation.method(#listReports, []),
            returnValue: _i3.Future<List<_i2.Report>>.value(<_i2.Report>[]),
          )
          as _i3.Future<List<_i2.Report>>);

  @override
  _i3.Future<_i2.Report> getReportOrEmpty(String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#getReportOrEmpty, [fileId]),
            returnValue: _i3.Future<_i2.Report>.value(
              _FakeReport_0(
                this,
                Invocation.method(#getReportOrEmpty, [fileId]),
              ),
            ),
          )
          as _i3.Future<_i2.Report>);

  @override
  _i3.Future<_i4.Uint8List> downloadPdfBytes(String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#downloadPdfBytes, [fileId]),
            returnValue: _i3.Future<_i4.Uint8List>.value(_i4.Uint8List(0)),
          )
          as _i3.Future<_i4.Uint8List>);
}
